### ISSUE TITLE
Build for A500M

### ISSUE THREAD

**Issue by codebseraph** [DeadSquirrel01/lineage-15_a5_releases#2]
Hello Marco,
I want try to build LOS 15.1 for A500M, you can tell which device tree from your sources i need? Since A500FU have more system partition size, the builds doesn't install with block-based OTA enabled.

**Comment by DeadSquirrel01** [comment]
I use the sources of a5-common tree that i havent uploaded, yet. Only kernel sources are available. To install on M you need to create a zip like my lineage 14 one

**Comment by codebseraph** [comment]
Thanks for the info, i'll wait and try install the ROM with that method.
