### ISSUE TITLE
Problem with Line 15.1 - 02/10/2018

### ISSUE THREAD

**Issue by pedrohrqe** [DeadSquirrel01/lineage-15_a5_releases#6]
Problem with Line 15.1 - 02/10/2018
I can not install on the a500M, give an error 7 or incompatible, how do I get the ROM installed?
E1001: Failed to update system image.
The problem is caused by the block image update on update script, which did not occur in the build of 11/01/2018.
Whenever a new build comes out there is no way to install

**Comment by DeadSquirrel01** [comment]
No comment
